default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: moneymanage_development 

production:
  <<: *default
  database: moneymanage_production
  username: moneymanage
  password: password